# SQL Server connection properties
#db.url=jdbc:sqlserver://139.59.4.149:1433;databaseName=LetterOfCreditDB;encrypt=false;trustServerCertificate=true

#db.url=jdbc:sqlserver://10.1.1.229:1433;databaseName=LetterOfCreditDB;encrypt=false;trustServerCertificate=true

db.url=jdbc:sqlserver://SC-US-PG04L6VJ\\SQLEXPRESS:1433;databaseName=LetterOfCreditDB;encrypt=false;trustServerCertificate=true

db.password=Shaad1234snak@
db.username=sa
#db.password=admin@123
#db.password=SnaK@5421I
db.pool.size=10

# File storage
upload.base.dir=${catalina.base}/lc-uploads
report.base.dir=${catalina.base}/lc-reports
