# SQL Server connection properties
db.url=jdbc:sqlserver://139.59.4.149:1433;databaseName=LetterOfCreditDB;encrypt=false;trustServerCertificate=true
db.username=sa
db.password=SnaK@5421I
db.pool.size=10

# File storage
upload.base.dir=${catalina.base}/lc-uploads
report.base.dir=${catalina.base}/lc-reports
